<?php

namespace ContainerVCTCpfN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1lXs1cnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1lXs1cn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1lXs1cn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'post' => ['privates', '.errored..service_locator.1lXs1cn.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.1lXs1cn": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'managerRegistry' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
