<?php

namespace ContainerVCTCpfN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZlGEdz8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zlGEdz8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zlGEdz8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUpload' => ['privates', 'App\\Services\\FileUpload', 'getFileUploadService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'post' => ['privates', '.errored..service_locator.zlGEdz8.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.zlGEdz8": it references class "App\\Entity\\Post" but no such service exists.'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'fileUpload' => 'App\\Services\\FileUpload',
            'managerRegistry' => '?',
            'post' => 'App\\Entity\\Post',
            'security' => '?',
        ]);
    }
}
