<?php

namespace ContainerVCTCpfN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\FileUpload' shared autowired service.
     *
     * @return \App\Services\FileUpload
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FileUpload.php';

        return $container->privates['App\\Services\\FileUpload'] = new \App\Services\FileUpload($container);
    }
}
