<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DGU3S0RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DGU3S0R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DGU3S0R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentController::deleteComment' => ['privates', '.service_locator.6NgsqK_', 'get_ServiceLocator_6NgsqKService', true],
            'App\\Controller\\CommentController::editComment' => ['privates', '.service_locator.6NgsqK_', 'get_ServiceLocator_6NgsqKService', true],
            'App\\Controller\\CommentController::likeComment' => ['privates', '.service_locator.6NgsqK_', 'get_ServiceLocator_6NgsqKService', true],
            'App\\Controller\\PostController::MobileDelete' => ['privates', '.service_locator.uPKkxqj', 'get_ServiceLocator_UPKkxqjService', true],
            'App\\Controller\\PostController::Mobilenew' => ['privates', '.service_locator.uPKkxqj', 'get_ServiceLocator_UPKkxqjService', true],
            'App\\Controller\\PostController::Mobileupdate' => ['privates', '.service_locator.uPKkxqj', 'get_ServiceLocator_UPKkxqjService', true],
            'App\\Controller\\PostController::delete' => ['privates', '.service_locator.t1TstrH', 'get_ServiceLocator_T1TstrHService', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.zlGEdz8', 'get_ServiceLocator_ZlGEdz8Service', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.tRDK7rj', 'get_ServiceLocator_TRDK7rjService', true],
            'App\\Controller\\PostController::indexF' => ['privates', '.service_locator.tRDK7rj', 'get_ServiceLocator_TRDK7rjService', true],
            'App\\Controller\\PostController::like' => ['privates', '.service_locator.1lXs1cn', 'get_ServiceLocator_1lXs1cnService', true],
            'App\\Controller\\PostController::postMobileshow' => ['privates', '.service_locator.LiOQ1Rg', 'get_ServiceLocator_LiOQ1RgService', true],
            'App\\Controller\\PostController::postmobile' => ['privates', '.service_locator.GAsXfVE', 'get_ServiceLocator_GAsXfVEService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.bLcVwFI', 'get_ServiceLocator_BLcVwFIService', true],
            'App\\Controller\\RegistrationController::registerUser' => ['privates', '.service_locator.vO1lrL7', 'get_ServiceLocator_VO1lrL7Service', true],
            'App\\Controller\\SecurityController::adminLogin' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CommentController:deleteComment' => ['privates', '.service_locator.6NgsqK_', 'get_ServiceLocator_6NgsqKService', true],
            'App\\Controller\\CommentController:editComment' => ['privates', '.service_locator.6NgsqK_', 'get_ServiceLocator_6NgsqKService', true],
            'App\\Controller\\CommentController:likeComment' => ['privates', '.service_locator.6NgsqK_', 'get_ServiceLocator_6NgsqKService', true],
            'App\\Controller\\PostController:MobileDelete' => ['privates', '.service_locator.uPKkxqj', 'get_ServiceLocator_UPKkxqjService', true],
            'App\\Controller\\PostController:Mobilenew' => ['privates', '.service_locator.uPKkxqj', 'get_ServiceLocator_UPKkxqjService', true],
            'App\\Controller\\PostController:Mobileupdate' => ['privates', '.service_locator.uPKkxqj', 'get_ServiceLocator_UPKkxqjService', true],
            'App\\Controller\\PostController:delete' => ['privates', '.service_locator.t1TstrH', 'get_ServiceLocator_T1TstrHService', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.zlGEdz8', 'get_ServiceLocator_ZlGEdz8Service', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.tRDK7rj', 'get_ServiceLocator_TRDK7rjService', true],
            'App\\Controller\\PostController:indexF' => ['privates', '.service_locator.tRDK7rj', 'get_ServiceLocator_TRDK7rjService', true],
            'App\\Controller\\PostController:like' => ['privates', '.service_locator.1lXs1cn', 'get_ServiceLocator_1lXs1cnService', true],
            'App\\Controller\\PostController:postMobileshow' => ['privates', '.service_locator.LiOQ1Rg', 'get_ServiceLocator_LiOQ1RgService', true],
            'App\\Controller\\PostController:postmobile' => ['privates', '.service_locator.GAsXfVE', 'get_ServiceLocator_GAsXfVEService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.bLcVwFI', 'get_ServiceLocator_BLcVwFIService', true],
            'App\\Controller\\RegistrationController:registerUser' => ['privates', '.service_locator.vO1lrL7', 'get_ServiceLocator_VO1lrL7Service', true],
            'App\\Controller\\SecurityController:adminLogin' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CommentController::deleteComment' => '?',
            'App\\Controller\\CommentController::editComment' => '?',
            'App\\Controller\\CommentController::likeComment' => '?',
            'App\\Controller\\PostController::MobileDelete' => '?',
            'App\\Controller\\PostController::Mobilenew' => '?',
            'App\\Controller\\PostController::Mobileupdate' => '?',
            'App\\Controller\\PostController::delete' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::indexF' => '?',
            'App\\Controller\\PostController::like' => '?',
            'App\\Controller\\PostController::postMobileshow' => '?',
            'App\\Controller\\PostController::postmobile' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Controller\\RegistrationController::registerUser' => '?',
            'App\\Controller\\SecurityController::adminLogin' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommentController:deleteComment' => '?',
            'App\\Controller\\CommentController:editComment' => '?',
            'App\\Controller\\CommentController:likeComment' => '?',
            'App\\Controller\\PostController:MobileDelete' => '?',
            'App\\Controller\\PostController:Mobilenew' => '?',
            'App\\Controller\\PostController:Mobileupdate' => '?',
            'App\\Controller\\PostController:delete' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:indexF' => '?',
            'App\\Controller\\PostController:like' => '?',
            'App\\Controller\\PostController:postMobileshow' => '?',
            'App\\Controller\\PostController:postmobile' => '?',
            'App\\Controller\\PostController:show' => '?',
            'App\\Controller\\RegistrationController:registerUser' => '?',
            'App\\Controller\\SecurityController:adminLogin' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
