<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T1TstrHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t1TstrH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t1TstrH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'fileUpload' => ['privates', 'App\\Services\\FileUpload', 'getFileUploadService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'post' => ['privates', '.errored..service_locator.t1TstrH.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.t1TstrH": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'fileUpload' => 'App\\Services\\FileUpload',
            'managerRegistry' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
