<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BLcVwFIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bLcVwFI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bLcVwFI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blogPagination' => ['privates', 'App\\Services\\BlogPagination', 'getBlogPaginationService', true],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'post' => ['privates', '.errored..service_locator.bLcVwFI.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.bLcVwFI": it references class "App\\Entity\\Post" but no such service exists.'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'blogPagination' => 'App\\Services\\BlogPagination',
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'doctrine' => '?',
            'post' => 'App\\Entity\\Post',
            'security' => '?',
        ]);
    }
}
