<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VO1lrL7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vO1lrL7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vO1lrL7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticator' => ['privates', 'App\\Security\\CustomLoginAuthenticator', 'getCustomLoginAuthenticatorService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUpload' => ['privates', 'App\\Services\\FileUpload', 'getFileUploadService', true],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'authenticator' => 'App\\Security\\CustomLoginAuthenticator',
            'em' => '?',
            'fileUpload' => 'App\\Services\\FileUpload',
            'userAuthenticator' => '?',
            'userPasswordHasher' => '?',
        ]);
    }
}
