<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TRDK7rjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tRDK7rj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tRDK7rj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blogPagination' => ['privates', 'App\\Services\\BlogPagination', 'getBlogPaginationService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'fileUpload' => ['privates', 'App\\Services\\FileUpload', 'getFileUploadService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'blogPagination' => 'App\\Services\\BlogPagination',
            'doctrine' => '?',
            'fileUpload' => 'App\\Services\\FileUpload',
            'postRepository' => 'App\\Repository\\PostRepository',
            'security' => '?',
        ]);
    }
}
