<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6NgsqKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6NgsqK_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6NgsqK_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.6NgsqK_.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.6NgsqK_": it references class "App\\Entity\\Comment" but no such service exists.'],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'managerRegistry' => '?',
        ]);
    }
}
