<?php

namespace ContainerGhJcEUi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPaginationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\BlogPagination' shared autowired service.
     *
     * @return \App\Services\BlogPagination
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'BlogPagination.php';

        $a = ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService'));

        if (isset($container->privates['App\\Services\\BlogPagination'])) {
            return $container->privates['App\\Services\\BlogPagination'];
        }

        return $container->privates['App\\Services\\BlogPagination'] = new \App\Services\BlogPagination(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), $a);
    }
}
