<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVCTCpfN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVCTCpfN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVCTCpfN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVCTCpfN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVCTCpfN\App_KernelDevDebugContainer([
    'container.build_hash' => 'VCTCpfN',
    'container.build_id' => '6b65a018',
    'container.build_time' => 1683823042,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVCTCpfN');
